### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by kattweigh** [npbhavya/Kraken2-output-manipulation#4]
Hi there,

I've run Kraken2 on all of my samples using the following script:
```
for i in `ls *.fasta.gz`; do
  kraken2 -threads 1 --db /safs-data02/dennislab/db/kraken2/nr_2021_07_28/ --use-names --report /safs-data01/uqkweigh/pacbio/kraken2/bact/${i%fasta.gz}kraken_report --report-zero-counts --output /safs-data01/uqkweigh/pacbio/kraken2/bact/${i%fasta.gz}kraken.out ${i}
done
```

I've then been trying to summarise the output from each sample by running the kraken-multiple-taxa2.py script on a directory containing my kraken reports using:
```
load_python37
python kraken-multiple-taxa.py -d kraken_report/ -r F -c 2 -o kraken-report-final
```

However, I'm running into the following error:
```
Checking input file done
Traceback (most recent call last):
  File "kraken-multiple-taxa2.py", line 60, in <module>
    kraken_cat_report(results.directory, results.rank, results.column, results.output)
  File "kraken-multiple-taxa2.py", line 22, in kraken_cat_report
    fields=line.split('\t')
TypeError: a bytes-like object is required, not 'str'
```

I have tried the alternative python script, 'kraken-multiple.py', and also get the same error.

Any suggestions would be greatly appreciated. Thank you!

**Comment by kattweigh** [comment]
I believe this was because I was loading an old version of python.
